### ISSUE TITLE
All the navigation pages like home, about us, contact us, etc. look very simple

### ISSUE THREAD

**Issue by nishtha-902** [gauravsingh1281/Rentalog.in--Frontend#123]
I can enhance CSS of all navigation pages so that it will look attractive and eye catchy. Please assign me this issue. I will ensure the positioning of buttons and alignment of text and will add some colours so that it look attractive.

**Comment by nishtha-902** [comment]
Is this issue assigned to me, Can I start making changes in this?

**Comment by Codewithmeowmeow** [comment]
I would like to work on this issue kindly assign it to me.

**Comment by sejals23** [comment]
I would really like to take up the issue...and I can enhance your pages in presentable manner....Since I am a experienced web developer with live projects....

**Comment by gauravsingh1281** [comment]
@nishtha-902 assigned 🚀

**Comment by nishtha-902** [comment]
@gauravsingh1281 thanks for assigning

**Comment by gauravsingh1281** [comment]
@nishtha-902 ?
