### ISSUE TITLE
 Missing Smooth Border Radius for Game Cells

### ISSUE THREAD

**Issue by Vishwajeet594** [gauravsingh1281/Rentalog.in--Frontend#125]
**Description: The Tic Tac Toe game cells lack a smooth border radius, giving the game grid a sharp, blocky appearance. This affects the visual aesthetics, making the design appear less polished.**

**Please add a smooth border radius to the game cells (e.g., 5-10px) to create rounded corners. This will give the grid a more modern and refined look, enhancing the user experience.**

**Comment by sejals23** [comment]
I would really like to take up the issue....Since I am a experienced web developer....I can make you assure that it will be eye catchy...and Over that I ll add color to the border to enhance its beauty..
