### ISSUE TITLE
Create a New Page for Tic Tac Toe Game Rules

### ISSUE THREAD

**Issue by Vishwajeet594** [gauravsingh1281/Rentalog.in--Frontend#126]
### Description: 
**Currently, the rules of Tic Tac Toe are displayed directly on the main game screen. This makes the game interface cluttered and could distract from the playing experience. To improve user experience and maintain a clean interface, a separate page should be created where users can read the game rules in detail.**

**Comment by Codewithmeowmeow** [comment]
Kindly assign it to me i would love to work on this issue.

**Comment by Pujitha254** [comment]
Hey Gaurav!! just checked your project its pretty good. If there is a new page for TicTacToe Game rules it will be more clear .So could you please assign this to me.

Please assign me this issue @gauravsingh1281

**Comment by sejals23** [comment]
Could you please assign this to mee...I can do it...since I am a experienced web developer

**Comment by gauravsingh1281** [comment]
Hey @Pujitha254 @Codewithmeowmeow @Vishwajeet594 @sejals23, this project is not related to the Tic-Tac-Toe game. Please read the project readme for project details.
