### ISSUE TITLE
Design proper button with icons in the login page for login using facebook and google

### ISSUE THREAD

**Issue by v-280** [gauravsingh1281/Rentalog.in--Frontend#127]
![Screenshot 2024-10-01 182425](https://github.com/user-attachments/assets/c8c96c91-3622-4553-839f-ce77eac43471)
Could you please assign this issue to me under GSSOC'24 extd?

**Comment by v-280** [comment]
so should this issue assigned to me so that I can start working on it?

**Comment by Codewithmeowmeow** [comment]
Kindly assign me this issue i would love to work on this.

**Comment by gauravsingh1281** [comment]
@v-280 assigned 🚀

**Comment by Ishajain0** [comment]
@gauravsingh1281 assign this task to me I would like to work on it...

**Comment by v-280** [comment]
@gauravsingh1281 thankyou!
