### ISSUE TITLE
enhance navbar and signup page

### ISSUE THREAD

**Issue by sanayamahajan-23** [gauravsingh1281/Rentalog.in--Frontend#128]
improve the navbar design and signup page design since they look really basic

**Comment by iamsohelx** [comment]
Hi @gauravsingh1281 i can help you to improve ui of your website and register page, by adding proper fonts and icons for your website and also adjust padding, margin, i would be great if you give me this opportunity, could you please assign me this issue with label

**Comment by sejals23** [comment]
Could you please assign this to me.....I am an experienced web developer....so hereby I can enhance your website in a much better way.

**Comment by gauravsingh1281** [comment]
@sanayamahajan-23 assigned 🚀

**Comment by gauravsingh1281** [comment]
@iamsohelx ?
