### ISSUE TITLE
Enhancing colour of website

### ISSUE THREAD

**Issue by Codewithmeowmeow** [gauravsingh1281/Rentalog.in--Frontend#130]
I would like to give beautiful and elegant colours to the website to make it more attractive.
Kindly add labels.

**Comment by SHRAVANIc01** [comment]
I want to enhance the website with beautiful and elegant colors to make it more appealing.
assign this task to me. [@Codewithmeowmeow ]

**Comment by gauravsingh1281** [comment]
Hey @Codewithmeowmeow, please provide more information on how you can enhance the design of Rentalog.in. If you have any rough designs, please share them

**Comment by gauravsingh1281** [comment]
@SHRAVANIc01 ?

**Comment by SHRAVANIc01** [comment]
was busy with other stuff, i will work on it for sure.
