### ISSUE TITLE
Change the Icon of Twitter to X And can Add more Icons.

### ISSUE THREAD

**Issue by Bhanuprakash842** [gauravsingh1281/Rentalog.in--Frontend#131]
I want to change all the icons of the twitter which are present in the website to X icon And add more icons if needed. I Would be Grateful if you Assign this issue to me with label **Gssoc-ext,hacktoberfest** and My github account @Bhanuprakash842
![image](https://github.com/user-attachments/assets/5296e8dc-c4f8-493d-8813-bd01390703f5)
![image](https://github.com/user-attachments/assets/c87e4214-95da-49cc-8915-799050203040)

**Comment by Devanshu1603** [comment]
please assign this issue to me under gssoc ext

**Comment by bv29** [comment]
please assign this issue to me under GSSoC-Ext

**Comment by YooAshu** [comment]
@gauravsingh1281 as this is not resolved yet please assign me this

**Comment by bv29** [comment]
please assign this issue to me under GSSoC-Ext, as I've already solved the problem.
