### ISSUE TITLE
Icon for Google is not displayed properly

### ISSUE THREAD

**Issue by Sameeratweb** [gauravsingh1281/Rentalog.in--Frontend#133]
Icon for Google is not displayed properly.Instead, it shows a broken image placeholder .
I can work for this issue please allow me with issue and relevant tags under GSSoC'24-Extd.

**Comment by SHRAVANIc01** [comment]
assign this issue to me, i can help you. [  @Sameeratweb ]

**Comment by Qamreen22** [comment]
I can work on issue #133

**Comment by Sameeratweb** [comment]
![Screenshot 2024-10-04 144733](https://github.com/user-attachments/assets/3074bfff-b53a-40cc-a3bd-b10f12375607)
from i end issue is being resolved. please check and let me know.
