### ISSUE TITLE
Adding dark mode

### ISSUE THREAD

**Issue by mahitha63** [gauravsingh1281/Rentalog.in--Frontend#145]
![image](https://github.com/user-attachments/assets/904aa862-325a-4784-8c8d-8f9f4dfc8416)
The actual bright mode is good. /But adding a dark mode makes it beautiful for an amazing experience. 
So, I would like to take the initiative to add Dark Mode to this site. 
@gauravsingh1281   assign this issue to me.

**Comment by sanjay-kv** [comment]
@mahitha63 i wont be able to assign issue on other people repo. I'm here to manage labels. 

you may need to tag project admin or mentor for this

**Comment by Dhruv-pahuja** [comment]
I would like to work on this , Can you please assign it to me ..
@mahitha63

**Comment by T-Rahul-prabhu-38** [comment]
@gauravsingh1281  since there hasnt been any updates on this work , can you please assign me this task , ill quickly finish the task.

**Comment by gauravsingh1281** [comment]
@mahitha63 ?

**Comment by mahitha63** [comment]
@gauravsingh1281 I have not yet submitted the changes as I am currently in the middle of my exams, which will continue until next Saturday.

If the submission is urgent, please assign the task to someone else who might be available to complete it sooner. Otherwise, I would be happy to finish it once my exams are over and submit it shortly after.

Please let me know how you'd like to proceed. Thank you for being so understanding.

**Comment by Dhruv-pahuja** [comment]
@gauravsingh1281 so can you assign it to me

**Comment by Dhruv-pahuja** [comment]
> @gauravsingh1281 I have not yet submitted the changes as I am currently in the middle of my exams, which will continue until next Saturday.
> 
> If the submission is urgent, please assign the task to someone else who might be available to complete it sooner. Otherwise, I would be happy to finish it once my exams are over and submit it shortly after.
> 
> Please let me know how you'd like to proceed. Thank you for being so understanding.


@gauravsingh1281 so can please assign it to me

**Comment by Dhruv-pahuja** [comment]
@gauravsingh1281 can i work on this ??

**Comment by Dhruv-pahuja** [comment]
@gauravsingh1281 ??

**Comment by T-Rahul-prabhu-38** [comment]
can u assign me then.
