### ISSUE TITLE
Re designing the rentalogin 

### ISSUE THREAD

**Issue by Aazib-at-hub** [gauravsingh1281/Rentalog.in--Frontend#146]
Re designing the home page of the rentalogin and adding scroll down option instead of taking it to the diffirent page and adding images to the site for better feel and interactive interface and changing the design of button used here.
![WhatsApp Image 2024-10-02 at 18 11 09 (1)](https://github.com/user-attachments/assets/5c176394-80ba-4e63-a324-4154783e6b83)

something like this.

**Comment by Aazib-at-hub** [comment]
> Congratulations, @Aazib-at-hub! 🎉 Thank you for creating your issue for Rentalog. Your contribution is greatly appreciated and we look forward to working with you to resolve the issue. Keep up the great work! Should you have any queries or require guidance, do not hesitate to ask.

shall i start working.

**Comment by RIYA-YADAV-19** [comment]
I’ve been reviewing the current design of the Rentalogin page, and I believe a redesign could greatly enhance its usability and appeal. Improving the visual layout and user flow could make the login process more intuitive and engaging, which would benefit users by providing a smoother experience. I would love to take on the task of redesigning the Rentalogin page to make it more modern and user-friendly. Could I be assigned this task?

**Comment by gauravsingh1281** [comment]
Hey @RIYA-YADAV-19 @Aazib-at-hub, you can both work on this issue together. I'll choose the design that I find better.

**Comment by RIYA-YADAV-19** [comment]
> Hey @RIYA-YADAV-19 @Aazib-at-hub, you can both work on this issue together. I'll choose the design that I find better.

I will do it surely, Thank You for Considering me for this opportunity.

**Comment by Aazib-at-hub** [comment]
> Hey @RIYA-YADAV-19 @Aazib-at-hub, you can both work on this issue together. I'll choose the design that I find better.

Thanks for the opportunity, hope to get it very soon.

**Comment by Aazib-at-hub** [comment]
I have completed #196 #197 #198 #199 @gauravsingh1281
