### ISSUE TITLE
Nav bar functionality and UI

### ISSUE THREAD

**Issue by bvvivek6** [gauravsingh1281/Rentalog.in--Frontend#147]
If i scroll, the nav does not indicate on which section i'm in. For example, if i'm in home, its not indicating. If i click about, it gets highlighted. But if i scroll back to home, it still shows that im in contact section.  And also we can make the nav more attractive adding a blur to it enhancing the UI.

**Adding the logo to be functional**. When i click the logo, it should take me to the home page. Enhances the UX and usability

Kindly assign me this project for adding these features to your project.

**Comment by SRN-Ranjan** [comment]
@gauravsingh1281 since this issue is still pending, please assign me to complete the task quickly .
