### ISSUE TITLE
Enhancing the UI by Animation and making it responsive 

### ISSUE THREAD

**Issue by RIYA-YADAV-19** [gauravsingh1281/Rentalog.in--Frontend#148]
I’ve been reviewing the current design of the Rentalogin page, and I believe a redesign could greatly enhance its usability and appeal. Improving the visual layout and user flow could make  it more intuitive and engaging, which would benefit users by providing a smoother experience. I would love to take on the task of redesigning the Rentalogin page to make it more modern and user-friendly. Could I be assigned this task?

**Comment by gauravsingh1281** [comment]
I've assigned issue #146 to you because it is the same as the other issue, and you also commented on it.

**Comment by RIYA-YADAV-19** [comment]
> Hey @RIYA-YADAV-19 I've assigned issue #146 to you because it is the same as the other issue, and you also commented on it.

Yes , I just saw it , will do it
