### ISSUE TITLE
Favicon is missing in all pages

### ISSUE THREAD

**Issue by Suvadip-sana** [gauravsingh1281/Rentalog.in--Frontend#149]
Hi! I am Suvadip Sana

**ISSUE** Favicon is missing in all pages. I want to work on it.

**Suggestion**
I add the favicon same as Logo that displayed on Home page.

Please assign me that issue. I want to work on it.

**Comment by Suvadip-sana** [comment]
Ok wait

**Comment by Suvadip-sana** [comment]
![image](https://github.com/user-attachments/assets/0ce32aed-704c-498a-95bb-e85e2b8d03ec)
Here is the screensort. 
See the favicon was not there. I want to add this logo as favicon.



Please assign me that issue! I want to fix it properly for every pages.

**NOTE** expected labels - hacktoberfest, gssoc-exted, point label.

**Comment by Suvadip-sana** [comment]
Could you please assign to me?

**Comment by gauravsingh1281** [comment]
Hey @Suvadip-sana you find the issue on the main website but currently, we want the contribution to this repo.
