### ISSUE TITLE
animation on scroll

### ISSUE THREAD

**Issue by YooAshu** [gauravsingh1281/Rentalog.in--Frontend#156]
adding animation on scroll will be very good for UI, so please assign me this i can add different animation on scrolling

**Comment by theyashdhiman04** [comment]
I would like to implement animations triggered by scrolling to enhance the user experience. As users scroll through the page, certain elements should animate into view, drawing attention and improving engagement.

**Comment by gauravsingh1281** [comment]
Hey @YooAshu @theyashdhiman04 what type of animation do you use show some examples.

**Comment by YooAshu** [comment]
@gauravsingh1281 animation using animation on scroll library , animation like fading from left or right like any minimal website
