### ISSUE TITLE
adding Carousel

### ISSUE THREAD

**Issue by YooAshu** [gauravsingh1281/Rentalog.in--Frontend#157]
adding automatic scrolling carousel (fading)at the top part of website, assign me for this feature 
![image](https://github.com/user-attachments/assets/9e69d362-8fc1-44f3-bde0-f9f04ed6fe5f)

**Comment by itsmeAYUSH** [comment]
Could you please assign this issue to me under GSSOC'24 extd and Hacktoberfest?
I would like to work on adding Carousel and make it more user-friendly. Thanks!

**Comment by YooAshu** [comment]
I will make a PR today, don't worry
