### ISSUE TITLE
ADD: Create a FAQ page

### ISSUE THREAD

**Issue by samyak-aditya** [gauravsingh1281/Rentalog.in--Frontend#161]
I propose to add a new FAQ page on the website where users can find Frequently asked questions about the platform Rentalog.in.
Hey @gauravsingh1281 Please assign this task to me

**Comment by Anshika09Singh** [comment]
I want to resolve this issue and contribute my work please give me chance.

**Comment by gauravsingh1281** [comment]
@Anshika09Singh assigned 🚀

**Comment by Anshika09Singh** [comment]
i solve issue and make changes on faq pages but i can not show my changes in your repository

**Comment by Anshika09Singh** [comment]
done i resolve your issue of  faq page 
check it

**Comment by Anshika09Singh** [comment]
i have mistake clickin in unassigned so sorry

**Comment by manastiwari99** [comment]
I would like to work Please assign it to me

**Comment by nithin17298** [comment]
@gauravsingh1281  I want to resolve this issue please assign me
