### ISSUE TITLE
i want to add a dark-light toggle button where users can use the UI based on their preference

### ISSUE THREAD

**Issue by mrpeace07** [gauravsingh1281/Rentalog.in--Frontend#164]
if u can assign this task and mark it with the appropriate tag ill soon start working on it..

**Comment by theyashdhiman04** [comment]
I would like to add a dark-light mode toggle button to allow users to switch between dark and light themes based on their preference. This will improve the user experience, providing a more accessible and customizable interface.
Solution:
Implement a toggle button in the UI that switches between dark and light modes.
Ensure that all UI components are styled properly for both themes.
