### ISSUE TITLE
social media icons in Login page and signup or not good

### ISSUE THREAD

**Issue by saimohan11** [gauravsingh1281/Rentalog.in--Frontend#166]
Assign me this task with labels
, gssoc-ext
,hacktoberfest,hacktoberfest-accepted,Level-1

**Comment by itsmeAYUSH** [comment]
Could you please assign this issue to me under GSSOC'24 extd and Hacktoberfest?
I would like to work on Login page and signup page and make it more user-friendly . Thanks!
