### ISSUE TITLE
feature enhancement : Dark mode Toggle

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [gauravsingh1281/Rentalog.in--Frontend#175]
### **Is your feature request related to a problem? Please describe.**
there is no preferences in the website to toggle between dark and light mode. I will create a toggle in the navabar which will allow the user to toggle between dark mode and light mode.

**Comment by Sadab-Hussain** [comment]
Hi @gauravsingh1281,

Could you please assign this issue to me? I will do my best to make it user-interactive.

Thank you!
