### ISSUE TITLE
buttons of login and register page is not looking good.

### ISSUE THREAD

**Issue by rohitsharma2610** [gauravsingh1281/Rentalog.in--Frontend#209]
![image](https://github.com/user-attachments/assets/f0930de3-d6ba-4488-88e7-43627247925d)
i saw you website and it is great but in the login and register page, these buttons are not looking good. please assign me for this issue I'll add some styling on them.

**Comment by arpit74170** [comment]
give this task to me , i will help you out to enhance it with my great skills in website

**Comment by harshitkumargupta** [comment]
Hi @gauravsingh1281 
Can you please assign this task to me .

**Comment by bhaviya18** [comment]
hello @gauravsingh1281  can you kindly assign this issue to me

**Comment by gurramkarthiknetha** [comment]
give this task to me , i will help you out to enhance it with my great skills in website please assign it to me i will fix
