### ISSUE TITLE
Add a service section

### ISSUE THREAD

**Issue by 19Sonali** [gauravsingh1281/Rentalog.in--Frontend#212]
The current website lacks a dedicated services section.
I would like to add a services section based on the Figma design provided. 
Kindly assign this issue to me under Hacktoberfest and GSSoC-Extd labels. Below is a screenshot from the Figma design that serves as a reference:
![Screenshot 2024-10-05 222917](https://github.com/user-attachments/assets/aaf86bef-745e-46a3-83b6-3fc940e45f06)

**Comment by gauravsingh1281** [comment]
hey, @19Sonali, the services section has already been added you have to work on the enhancement design of the services section.

**Comment by 19Sonali** [comment]
Thank you for the update! In that case, I would love to work on enhancing the design of the services section.

**Comment by gauravsingh1281** [comment]
#254
