### ISSUE TITLE
[Bug] Login Fails to Redirect to Home Page After Successful Authentication

### ISSUE THREAD

**Issue by Dev-Rishav** [gauravsingh1281/Rentalog.in--Frontend#214]
**Description:**
After logging in with the provided credentials, the application does not navigate back to the home page as expected.

I would like to address this issue. If you would like me to proceed, please assign the relevant GSSoC labels. Thank you!

![Screenshot 2024-10-06 003906](https://github.com/user-attachments/assets/58a9dc4e-ff30-497d-b037-8009c03ef20b)

**Comment by KharjulSneha** [comment]
I'd like to work on this issue as part of GSSoC'24. Could you please assign it to me?
