### ISSUE TITLE
Redesign Rental Section Using Cards for a More Interactive Layout

### ISSUE THREAD

**Issue by ShradhaSaxena23** [gauravsingh1281/Rentalog.in--Frontend#244]
**Description:**
Currently, the rental section is displayed in a tabular format, which seems less engaging. I propose switching to a card-based design to make the interface more interactive and visually appealing.

**Objective:**

Replace the tabular layout with cards.
Each card will display key details like property images, price, location, and other relevant information.
This design will enhance user experience by making the section more intuitive and attractive.

**Benefits:**

A card layout provides a modern, responsive look.
Users can quickly scan through the available rentals without feeling overwhelmed by a table of data.

Please assign this task of designing layout under the label **Gssoc ext 2024 and Hacktoberfest-accepted**.

![Screenshot (170)](https://github.com/user-attachments/assets/f9a95046-5ccc-42a1-a2d3-a23ae7106b11)

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @gauravsingh1281
