### ISSUE TITLE
Redesigning login and signup pages

### ISSUE THREAD

**Issue by YooAshu** [gauravsingh1281/Rentalog.in--Frontend#265]
The current Login and signup pages look boring I can redesign it and can make it look cool

**Comment by aditi-agrawal12** [comment]
Hello @YooAshu 
I can add amazing colour scheme and add hover animations , I am deciding to add glassmorphism effect so that the page looks modern , please provide me with this issue so that I can make my first ever contribution😊

**Comment by YooAshu** [comment]
@aditi-agrawal12 hello , I am also a contributor so I can't do anything regarding this you can create a new issue on any repo to be assigned
