### ISSUE TITLE
[UI Enhancement] : Adding gsap animation to home page when loaded | gssoc-extd level 3

### ISSUE THREAD

**Issue by Hamza1821** [gauravsingh1281/Rentalog.in--Frontend#270]
### **Adding gsap animation to home page when loaded**

please assing this issue to me under gssoc-extd level 3

**Comment by aditi-agrawal12** [comment]
Hello @Hamza1821 
Please provide this issue to me , I can provide gsap animation as I have worked on this , and so that I can make my first contribution in open source 😊
