### ISSUE TITLE
[bug]: Login and Register Alert Issue - No Redirection to Home Page

### ISSUE THREAD

**Issue by angadnagar** [gauravsingh1281/Rentalog.in--Frontend#282]
## Issue Description

The login and register functionality is currently only displaying an alert message after successful authentication, but it is not redirecting the user to the home page as expected. This impacts the user experience by requiring manual navigation to the home page.

## Steps to Reproduce
1. Go to the login or register page.
2. Enter valid credentials and submit the form.
3. Observe the alert that confirms successful login or registration.
4. Note that the user remains on the same page instead of being redirected to the home page.

## Expected Behavior
- After a successful login or registration, the user should be automatically redirected to the home page.

## Actual Behavior
- Only an alert message is displayed, and the user is not redirected to the home page.

## Video

https://github.com/user-attachments/assets/f3f547eb-a01c-496b-bd14-e433c8d5086e

**Comment by gurramkarthiknetha** [comment]
I will contribute by improving the login and registration process to ensure users are automatically redirected to the home page after successful authentication. Currently, users only receive an alert confirming the login or registration, but they must manually navigate to the home page. I will review the existing code to find where the success messages are triggered and then add logic to redirect users to the home page immediately after login or registration. After making these changes, I will thoroughly test the functionality to confirm that the redirection works as expected, providing a smoother and more user-friendly experience.
