### ISSUE TITLE
Want to add  or change more css properties of the home page of the website

### ISSUE THREAD

**Issue by Dipanita45** [gauravsingh1281/Rentalog.in--Frontend#283]

**Comment by KhushiChauhan8** [comment]
Hi @gauravsingh1281 
I’m interested in working on the task to add or change more CSS properties on the home page. Could you please assign this issue to me? I’m ready to contribute and work on it.

Thank you!

Khushi Chauhan

**Comment by KhushiChauhan8** [comment]
Hello @gauravsingh1281 
I’m interested in working on the task to add or change more CSS properties on the home page. Could you please assign this issue to me? I’m ready to contribute and work on it.

Thank you!

**Comment by bhavana-katari** [comment]
I want to work it, Please assign it to me
