### ISSUE TITLE
Improve Interactivity on About Us Page by Adding Images/PNGs

### ISSUE THREAD

**Issue by veerendranadhkoppula** [gauravsingh1281/Rentalog.in--Frontend#288]
The current About Us page on the Rentalog website (https://www.rentalog.in/about) is static and lacks visual elements, making it less engaging for users. To enhance the user experience and make the page more interactive, I suggest the following improvements:

Suggested Improvements:
Add Illustrative Images/PNGs:

Include relevant images or icons that visually represent features like:
Property management
User-friendly interface
Support team assistance
This would help break up the text-heavy content and make the page more visually appealing.

**Comment by gauravsingh1281** [comment]
Hey @veerendranadhkoppula i want contributions on this site https://visionary-fenglisu-db1b1d.netlify.app/#home it is the updated design of rentalog.in

**Comment by Jiamir** [comment]
@gauravsingh1281 I would like to work on this issue. Could you please assign this to me and label it for Hacktoberfest?

**Comment by veerendranadhkoppula** [comment]
@gauravsingh1281 the current images on the Home Page of the website (https://visionary-fenglisu-db1b1d.netlify.app/#home) appear to be of low quality, which affects the visual appeal of the page. To enhance the website's professional appearance and user experience, I suggest replacing the existing images with higher-quality ones.

Suggested Improvements:
Replace Low-Quality Images:

The images on the Home Page should be replaced with higher-resolution alternatives to improve clarity and visual impact.
Ensure that the new images maintain fast loading speeds to avoid performance issues.
Optimization:

The new images should be optimized for web use (using formats like WebP or optimized PNG/JPG files) to maintain quality while ensuring quick load times.

**Comment by gauravsingh1281** [comment]
Same issue #310
