### ISSUE TITLE
Add backend for the contact form 

### ISSUE THREAD

**Issue by AyushSharma72** [gauravsingh1281/Rentalog.in--Frontend#304]
i want to setup backend to make  the contact form work
you can receive the email if the user via the form 

![image](https://github.com/user-attachments/assets/f54e7d40-9dfb-4297-b9a2-47c50518ba5a)

please assign this issue to me  @gauravsingh1281

**Comment by gauravsingh1281** [comment]
Hey @AyushSharma72  we currently want contributions on the frontend design.

**Comment by AyushSharma72** [comment]
> Hey @AyushSharma72 we currently want contributions on the frontend design.

Assign me any frontend issue you have ? @gauravsingh1281
