### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by isimarjitsingh** [gauravsingh1281/Rentalog.in--Frontend#323]
### 🐛 Bug Report

**Describe the bug**
As i observed your website does not have login/signup which is a little bit bug kinda. so i think you need to assign a developer who helps to develop a login/sign up page with a "validation" because without validation there is no point to make a login page .

Proposed Solution
please assign me this work because i am able to do authentication with the help of firebase and the designing of login/signup page.
and if you assign me this work i will try to submit it todays only

---

**To Reproduce**
1. Go to 'login page ' 
2. Click on 'Login  button'

4. See error 'it navigate us to home page without check that we are old users or not'

---

**Expected behavior**
we need to add "authentication" authentication means a feature which help old users to start from where they left it is like saving the process of all users .
---

**Screenshots**
now i am gonna attach a video which helps you to understand authentication ,and this authentication part is done by me

https://github.com/user-attachments/assets/6665921a-7f07-4062-9d5c-3ed68a4f1483

---

**Additional context**
please assign me this work i will love to contribute in it under gssoc extd.

---

**Severity**  
How critical is this issue?  
- [x ] 🔴 Critical  
- [ ] 🟠 Major  
- [ ] 🟡 Minor

---

**Possible Fix**  
you don't assign a backend developer 

---

### Checklist  
- [x ] I have searched the existing issues and this bug has not been reported yet.  
- [x ] I have updated the project to the latest version.  
- [ x] I have provided all the necessary details.  
- [x ] I have **starred this repository**.

**Comment by gauravsingh1281** [comment]
Hey @isimarjitsingh we currently want contributions on the frontend design.
