### ISSUE TITLE
[FEATURE] reputed mail services for signup's

### ISSUE THREAD

**Issue by smog-root** [gauravsingh1281/Rentalog.in--Frontend#326]
Modify the current signup process to validate email domains, allowing signups only from users with email addresses from trusted providers (e.g., Gmail, Outlook). 

Extract the domain from the user's email during signup and check it against a predefined list of trusted providers. 

If the domain is valid, continue the signup; otherwise, return an error message.

i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

@gauravsingh1281

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by smog-root** [comment]
I have already done the task and submitted the pull request! @SaanyaGarg5
