### ISSUE TITLE
Layout Responsiveness Issue in Services Section

### ISSUE THREAD

**Issue by gurramkarthiknetha** [gauravsingh1281/Rentalog.in--Frontend#327]
Description: The "Our Services are available in" section is not adapting well to the screen size. The images of New Delhi and Agra are displayed with significant white space around them, and their container does not seem to resize responsively, leading to a misalignment and underutilized space. This could be due to fixed dimensions, improper CSS grid or flex settings, or lack of responsive media queries
![image](https://github.com/user-attachments/assets/e797a60b-c2a8-431a-ae19-d957a33761cb)

**Comment by gurramkarthiknetha** [comment]
Please assign the issue to i will fix

**Comment by Deepanshi0019** [comment]
Hi, I see this issue is assigned to someone. I just wanted to know if anyone is actively working on it? If not, I'd like to help.
