### ISSUE TITLE
[FEATURE] the chatbot is not working ✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [gauravsingh1281/Rentalog.in--Frontend#346]
### 🚀 Feature Request

the chatbot is not working/not shown in the home page.
@gauravsingh1281 can you please assign me this task so i can work on it.

### Checklist  
- [X] I have checked the existing issues and this feature request is not a duplicate.  
- [X] I have **starred this repository**.  
- [X] I am willing to help implement this feature (optional).

**Additional context**

**Comment by Abishakm1507** [comment]
I'm an open-source contributor participating in the GirlScript Summer of Code, and I'm really interested in contributing to your project. I have experience in creating AI chatbot using Gemini API. Could you please assign this issue to me? I'm eager to contribute and improve the working of chatbot.
