### ISSUE TITLE
[Security] Password need to meet minimum requirements for signup.

### ISSUE THREAD

**Issue by smog-root** [gauravsingh1281/Rentalog.in--Frontend#361]
i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

Password Requirements:

At least 8 characters long.
At least 1 uppercase letter (A-Z).
At least 1 lowercase letter (a-z).
At least 1 number (0-9).
At least 1 special character (e.g., !@#$%^&*()).

Now, when a user tries to register, they will receive immediate feedback if their password does not meet these criteria. Let me know if you need any further changes or additional features!

**Comment by Keshav-1803** [comment]
Please assign this issue to me

**Comment by Keshav-1803** [comment]
@smog-root are you working on this issue ?

**Comment by smog-root** [comment]
@Keshav-1803 Yes!
