### ISSUE TITLE
[BUG] Navbar Layout Improper

### ISSUE THREAD

**Issue by Lokesh-Bijarniya** [gauravsingh1281/Rentalog.in--Frontend#364]
### 🐛 Bug Report

**Describe the bug**
The navbar items are not aligned correctly in a single line. Specifically, the Select Language dropdown appears visually out of alignment or detached from the Login and Register buttons, which breaks the design consistency.

---

**To Reproduce**
1. Go to the homepage of the website (refer to the screenshot).
2. Look at the navbar where the Home, Rentals, About, and Contact links are present.
3. Observe that the Select Language dropdown is placed on a different level compared to the Login and Register buttons. These elements should ideally be aligned in one horizontal row.

---

**Expected behavior**
All navbar elements, including Login, Register, and Select Language, should be aligned on a single horizontal line with equal spacing and consistent vertical alignment.

---

**Screenshots**

---

**Desktop (please complete the following information):**

---

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneSE]

---

**Additional context**
The issue might be due to improper flexbox or grid layout settings in the CSS. The container for the navbar elements may not have been correctly set to display its child elements inline or in a flex row.

---

**Screenshoots**
<img width="1440" alt="Screenshot 2024-10-14 at 4 27 52 PM" src="https://github.com/user-attachments/assets/2b0bbd1d-2946-4459-89ee-7a6e32cfe80a">

<img width="365" alt="Screenshot 2024-10-14 at 4 33 32 PM" src="https://github.com/user-attachments/assets/6a19e5e3-956c-40c4-aadb-bad5356ce4f4">

---

**Severity**  
How critical is this issue?  
- [ ] 🔴 Critical  
- [ ] 🟠 Major  
- [x] 🟡 Minor

---

**Possible Fix**  
The issue can be fixed by adjusting the CSS for the navbar. Use a flexbox layout (display: flex) or ensure that all elements are properly aligned in a single row with proper margins and padding between them.

---

### Checklist  
- [x] I have searched the existing issues and this bug has not been reported yet.  
- [x] I have updated the project to the latest version.  
- [x] I have provided all the necessary details.  
- [x] I have **starred this repository**.

**Comment by Subhajit-2023-44** [comment]
Duplicate #357
