### ISSUE TITLE
[FEATURE]: The icon on login pg 

### ISSUE THREAD

**Issue by SohamDas00** [gauravsingh1281/Rentalog.in--Frontend#365]
### 🚀 Feature Request

**Description**  
The icon on login pg 

---

**Problem Statement**  
The icon on login pg is shift upward

---

**Proposed Solution**  
The icon on login pg is shift upward so it shoud be inside the box

---

**Alternatives Considered**  
Have you considered any alternatives?  
If so, why did you choose this solution?

---

**Additional Context**  
Add any other context, screenshots, or details that would help explain your request.

---

### Checklist  
- [x] I have checked the existing issues and this feature request is not a duplicate.  
- [x] I have **starred this repository**.  
- [x] I am willing to help implement this feature (optional).

**Additional context**
![Screenshot 2024-10-14 165312](https://github.com/user-attachments/assets/2a2665c5-7db7-4152-a468-1d4210c28a89)

**Comment by Keshav-1803** [comment]
Please assign this issue to me

**Comment by SohamDas00** [comment]
you hav't got assigned to it
