### ISSUE TITLE
[FEATURE] : Icon in register page

### ISSUE THREAD

**Issue by SohamDas00** [gauravsingh1281/Rentalog.in--Frontend#366]
### 🚀 Feature Request

**Description**  
Icon in register page

---

**Problem Statement**  
Icon in register page where icon are getting of the box, 

---

**Proposed Solution**  
Icon in register page where icon are getting of the box,  so i can allign it to proper center of the box

---

**Alternatives Considered**  
Have you considered any alternatives?  
If so, why did you choose this solution?

---

**Additional Context**  
Add any other context, screenshots, or details that would help explain your request.

---

### Checklist  
- [x] I have checked the existing issues and this feature request is not a duplicate.  
- [x] I have **starred this repository**.  
- [x] I am willing to help implement this feature (optional).

**Additional context**
![Screenshot 2024-10-14 165625](https://github.com/user-attachments/assets/12c561cb-0eba-4e2a-9f4a-4634f67a64a2)

**Comment by SohamDas00** [comment]
please assign me this issue

**Comment by Subhajit-2023-44** [comment]
Duplicate #358

**Comment by SohamDas00** [comment]
you hav't got assigned to it

**Comment by Subhajit-2023-44** [comment]
> you hav't got assigned to it

@SohamDas00 Whoever finds the problem first and makes an assign request can fix the problem.      
You can check by going to another project...
