### ISSUE TITLE
[FEATURE]Decrease the height and of the nav bar

### ISSUE THREAD

**Issue by sanjanamb06** [gauravsingh1281/Rentalog.in--Frontend#369]
### 🚀 Feature Request

**Description**  
Decrease the height and size of the nav bar also increasing the background opacity .

---

**Problem Statement**  
Too fat in size it is taking a lot of space while scrolling.
---

**Proposed Solution**  
Decrease the height and size of the nav bar also increasing the background opacity .

---

**Additional Context**  

![Screenshot 2024-10-14 185431](https://github.com/user-attachments/assets/07d2073e-ec8f-49e8-8df3-eef5ef875f69)

---

### Checklist  
- [ /] I have checked the existing issues and this feature request is not a duplicate.  
- [ /] I have **starred this repository**.  
- [ /] I am willing to help implement this feature (optional).

**Additional context**

**Comment by Deepanshi0019** [comment]
Hi, I would like to work on this issue.

**Comment by sanjanamb06** [comment]
@gauravsingh1281 can you please assign me this issue i will resolve
