### ISSUE TITLE
[OTHER] Logo of google and facebook are not in their respective boxes

### ISSUE THREAD

**Issue by krish2366** [gauravsingh1281/Rentalog.in--Frontend#370]
### 📝 Other Issue

**Description**  
logo of google and facebook are not in their places in the register section.

![image](https://github.com/user-attachments/assets/977edce4-8d23-4736-9437-97f84845e3c9)

---

**Type of Issue**  
 🖼️ UI/UX Design

**Comment by krish2366** [comment]
assign me this task I'll do it quickly @gauravsingh1281

**Comment by AE-Hertz** [comment]
assign him

**Comment by krish2366** [comment]
thanks @AE-Hertz
