### ISSUE TITLE
Add Dark Mode to the website

### ISSUE THREAD

**Issue by Anjalis14** [gauravsingh1281/Rentalog.in--Frontend#389]
adding dark mode to the website

**Comment by Abishakm1507** [comment]
Can you please assign this to me under girlscript summer of code (gssoc-ext). I have experience in creating website with light and dark mode by using toggle button, user can switch between light mode and dark mode. Please assign this task to me I will complete this issue as soon as possible.

**Comment by Atul7307** [comment]
i work many website to create dark mode so please assign me
