### ISSUE TITLE
[FEATURE] : Adding animeted Pre Loader

### ISSUE THREAD

**Issue by AbhijitMotekar99** [gauravsingh1281/Rentalog.in--Frontend#405]
### Feature Description

The new feature is an animated preloader that would display while the website is loading its contents. The preloader would help enhance user experience by providing a smooth and visually appealing loading indicator before the main content of the site is fully rendered.

### Use Case

1. Initial Load Times: Users might experience slight delays due to larger assets or slow networks. The preloader would fill this gap, making the waiting time feel more fluid and professional.
2. First-Time Users: First-time users of the site may have slower load times as assets like images and scripts are fetched for the first time. The preloader would reassure them that content is being loaded.

### Benefits

1. Improved User Experience: Users won’t be left staring at a blank screen during loading times, which could otherwise lead to frustration or abandonment.
2. Enhanced Aesthetics: An animated preloader can add a professional touch, maintaining user engagement with an interesting visual instead of a plain loading bar.
3. Branding Opportunity: The preloader animation can incorporate elements of the website’s branding, such as its logo or color palette, helping to reinforce brand identity.

## Below one is sample video
https://github.com/user-attachments/assets/ab4e1fc8-54e5-4c2f-b58a-db67299b32af

**Comment by PulkitShubham** [comment]
@gauravsingh1281 Sir please assign this issue to me too

**Comment by Aditya-PS-05** [comment]
Can you assign me this issue?
