### ISSUE TITLE
[FEATURE]Enhance Navbar Aesthetics with Hover Effects and Improved Button Styles

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [gauravsingh1281/Rentalog.in--Frontend#411]
### 🚀 Feature Request
 
 

# Issue Description
In the current implementation of the navbar, the logo lacks any hover effect or animation, and the navigation items do not have an underline animation or any other engaging hover effects. To enhance the beauty of the navbar, I propose implementing the following changes:

1.Logo Animation: Add a hover effect or animation to the logo for improved interactivity.
2.Navigation Items: Implement underline animation or additional hover effects for nav items to make them more visually appealing.
3.Button Styles: Redesign the login and register options as buttons for better user experience.
4.Register Icon: Improve the design of the register icon for enhanced visibility and attractiveness.

---

**Additional Context**  
By incorporating these enhancements, we can significantly improve the aesthetics and usability of the navbar, providing users with a more engaging experience.

---
**Screenshot**
![navbar_navitems](https://github.com/user-attachments/assets/70dfa41e-7069-4e3e-85e1-6889aba2d806)

 
---

### Checklist  
- [] I have checked the existing issues and this feature request is not a duplicate.  
- [] I have **starred this repository**.  
- [x] I am willing to help implement this feature (optional).

**Comment by akilesh26** [comment]
Hi, I would like to work on this issue. Please assign me this and mark it under label "gssoc-ext"/"gssoc".
