### ISSUE TITLE
Customize scrollbar

### ISSUE THREAD

**Issue by ArchanRD** [gauravsingh1281/Rentalog.in--Frontend#421]
The scrollbar here looks off. Customizing the scrollbar will make it match to the theme of the website.

![image](https://github.com/user-attachments/assets/6f30ac06-4d58-4792-868e-7d3510259fc1)

**Comment by akshay0712-dev** [comment]
Can u please assign me this task

**Comment by ArchanRD** [comment]
@akshay0712-dev you need to create issue to get assigned. This is against the rules of gssoc.
