### ISSUE TITLE
[BUG] When we click on the icons like Google, Facebook, X and LinkedIn on the Login/Signup page so it redirects to the browser. It don't ask the user to select the account to perform login operation when the user is already logged in. 

### ISSUE THREAD

**Issue by NumlStudentSE** [gauravsingh1281/Rentalog.in--Frontend#458]
### 🐛 Bug Report

**Describe the bug**
When users attempt to sign up or log in using Google or other login methods where they are already logged in, the site does not prompt them to select an account. Instead, it redirects the user to the homepage e.g., www.google.com without presenting the account selection interface.

---

**To Reproduce**
1. Navigate to the signup/login page.
2. Select Google or any other login method.
3. Observe that no account selection prompt appears.
4. The default interface of that link appears like google.com.

---

**Expected behavior**
A prompt should appear asking the user to choose an account. 

---

**Screenshots**

Login page:
![image](https://github.com/user-attachments/assets/dca59810-bef4-4b93-9698-6293a0324f6e)

![image](https://github.com/user-attachments/assets/1532c0d6-4d53-4fd5-9f70-65b057160d8f)

Signup page:
![image](https://github.com/user-attachments/assets/2380868e-a067-468a-bfe9-df90252aa040)

![image](https://github.com/user-attachments/assets/61e9ef51-1c1e-4691-8d38-84c49e982cef)

---

**Environment (if applicable)**  
Provide relevant details about the environment where the issue occurred:  

**Desktop (please complete the following information):**

---

**Smartphone (please complete the following information):**

---

**Additional context**

---

**Severity**  
How critical is this issue?  
- [ ] 🟠 Major 

---

**Possible Fix**  
The possible solution could be implemented by identifying the relevant code logic regarding the login/signup page and then using best practices to implement the login operation using other options like Google, Facebook, X and LinkedIn.

---

### Checklist  
- [ ] I have searched the existing issues and this bug has not been reported yet.  
- [ ] I have updated the project to the latest version.  
- [done] I have provided all the necessary details.  
- [done] I have **starred this repository**.

**Comment by NumlStudentSE** [comment]
Please review and accept my bug report @gauravsingh1281

**Comment by gauravsingh1281** [comment]
Hey @NumlStudentSE  we currently want contributions on the frontend part of rentalog.in . You can work on the frontend part of the rentalog.in
