### ISSUE TITLE
Adding a Coming Soon Page For broken and not Working Links

### ISSUE THREAD

**Issue by coder-writes** [gauravsingh1281/Rentalog.in--Frontend#462]
# Issue Report

## Title
Proposal of Creating a Cooming Soon Page
## Description
There Are many Section in the Websties which are not fully Functional,there are many buttons, hyperlinks, and all which are not functional so we can create a Common Page for all Such elements in the page and then redirect all the elements to the same page as it will Create Positive Impact on the Users of the Web site . The Website Will feel Like Broken.

## Steps to Reproduce the Issue

1. **Action 1:** Make  a Coming Soon Page for all the upcoming Features
2. **Action 2:** Identify all the elements in the page that are not present now.
3. **Action 3:** Redirect all the elements to the same page

## Expected Behavior

![Screenshot 2024-10-22 071138](https://github.com/user-attachments/assets/c2405cea-a3f6-45f1-a72a-15e98bc18354)

## Actual Behavior

doing nothing

**Comment by kuldip40** [comment]
@gauravsingh1281 pls assign me this task. i will work on it.

**Comment by coder-writes** [comment]
@kuldip40  I am working on the issue and will submit my work by today's evening
