### ISSUE TITLE
[FEATURE] Adding a logout button

### ISSUE THREAD

**Issue by Stpchethan** [gauravsingh1281/Rentalog.in--Frontend#463]
The logout button ensures that users can securely terminate their sessions, preventing unauthorized access to their accounts or personal data.
![Screenshot (86)](https://github.com/user-attachments/assets/931e6282-4b49-4766-aee1-6d7e5b56dc3c)
Please aasign the issue 
GSsoc'24-Extended Contributor

**Comment by gauravsingh1281** [comment]
@Stpchethan where you want to add the logout button

**Comment by Stpchethan** [comment]
After the session completion of user

**Comment by Stpchethan** [comment]
Cool, I'll check it out.
