### ISSUE TITLE
[BUG] Footer section is repeating 

### ISSUE THREAD

**Issue by Priyanshi0112** [gauravsingh1281/Rentalog.in--Frontend#520]
### 🐛 Bug Report

**Describe the bug**
The website currently exhibits a bug where the footer section is unintentionally repeated on the page. This issue disrupts the user experience by cluttering the layout and creating confusion regarding the website's structure.

---

**Expected behavior**

---

**Screenshots**
![image](https://github.com/user-attachments/assets/861a8114-4bc5-44b7-828c-5b23e78c30d0)

---

**Environment (if applicable)**  
Provide relevant details about the environment where the issue occurred:  

**Desktop (please complete the following information):**

---

**Smartphone (please complete the following information):**

---

**Additional context**

---

**Severity**  
How critical is this issue?  
- [x] 🔴 Critical  
- [ ] 🟠 Major  
- [ ] 🟡 Minor

---

**Possible Fix**  
Suggest a fix or reason for the bug if known.

---

### Checklist  
- [x] I have searched the existing issues and this bug has not been reported yet.  
- [x] I have updated the project to the latest version.  
- [x] I have provided all the necessary details.  
- [x] I have **starred this repository**.

**Comment by anchalchaturvedi08** [comment]
Hello PA, May I also contribute to this issue?

**Comment by shibasarkar** [comment]
@gauravsingh1281 this issue was raised 2 days ago but not solved 
I would like to contribute to this issue 
could you please assign this to me
