### ISSUE TITLE
UI Bug: Logo and Heading Overlapping on Registration page

### ISSUE THREAD

**Issue by Raj-banerjee25** [gauravsingh1281/Rentalog.in--Frontend#541]
### 🐛 Bug Report

**Describe the bug**
There is a visual issue on the website where the logo and heading overlap. This affects readability and visual aesthetics, especially on smaller screens. This issue was observed in the Registration page.
---

**To Reproduce**
1. Go to the rentalog website.
2. Navigate to registration page
3, Observe the overlapping issue between the logo and heading.
---

**Expected behavior**
The logo and heading should have adequate spacing to ensure they are clearly visible and not overlapping.

---

**Screenshots**
Registration Page 
![ren1](https://github.com/user-attachments/assets/fb9ef000-1e02-4a28-9101-fb19fe47f761)

---

**Environment (if applicable)**  
Provide relevant details about the environment where the issue occurred:  

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome

---

**Smartphone (please complete the following information):**

---

**Additional context**
 This issue was observed when viewing the site,. The overlap affects the readability and overall user experience on these screens.

---

**Severity**  
How critical is this issue?  
- [ ] 🔴 Critical  
- [ ] 🟠 Major  
- [x] 🟡 Minor

---

**Possible Fix**  
The logo and heading should have adequate spacing to ensure they are clearly visible and not overlapping.

---

### Checklist  
- [x] I have searched the existing issues and this bug has not been reported yet.  
- [x] I have updated the project to the latest version.  
- [x] I have provided all the necessary details.  
- [x] I have **starred this repository**.

**Comment by Raj-banerjee25** [comment]
Please assign me this issue

**Comment by sachigoyal** [comment]
Can I work on  this issue?
