### ISSUE TITLE
[BUG]Duplicate Footer Display

### ISSUE THREAD

**Issue by amanver45** [gauravsingh1281/Rentalog.in--Frontend#544]
### Issue: Duplicate Footer Display

**Description:**  
The footer section appears twice on the page, creating a redundant display issue. This might be caused by the `Footer.ejs` component being rendered multiple times.

**Steps to Reproduce:**  
1. Open the [URL where the issue occurs] (e.g., Contact Us page).
2. Scroll to the bottom of the page.
3. Observe that the footer is displayed twice.

**Expected Behavior:**  
The footer should appear only once at the bottom of the page.

**Possible Solution:**  
- Check if `Footer' is being called twice in the main layout file.
- Review conditional statements to ensure the footer isn’t rendered twice under specific conditions.

---

Let me know if you need further customization!

**Severity**  
How critical is this issue?  
- [X] 🔴 Critical  
- [ ] 🟠 Major  
- [ ] 🟡 Minor

**Screenshots**
![Screenshot 2024-10-27 183543](https://github.com/user-attachments/assets/3c99efd8-b947-4b71-91d9-0d7f6d4d251c)

**Comment by akshay0712-dev** [comment]
Can u assign me this task
