### ISSUE TITLE
correcting the alignment of the nav bar .

### ISSUE THREAD

**Issue by Tanushree084** [gauravsingh1281/Rentalog.in--Frontend#581]
hey @gauravsingh1281 ,

i want to correct the alignment of the nav bar as the login and register is not suitable below the row of nav bar , not looking feasible .
currently it is looking like this :
<img width="944" alt="image" src="https://github.com/user-attachments/assets/39ecd432-3aab-49e1-b6b0-f091cc40eafc">

can you please assign me this issue , it would be grateful to work on this to make it look more consistent ?

**Comment by gayatrikate04** [comment]
can you assign me this issue

**Comment by gayatrikate04** [comment]
can you assign me this issue?
