### ISSUE TITLE
[BUG] Navbar overlapping on extra navber

### ISSUE THREAD

**Issue by PATILYASHH** [gauravsingh1281/Rentalog.in--Frontend#602]
### 🐛 Bug Report

**Describe the bug**
There are two navbar and they overlapping on each other 

---

**To Reproduce**
1. Go to 'website.'
2. See error

---

**Expected behavior**
There needed only one navbar 
---

**Screenshots**
![image](https://github.com/user-attachments/assets/de0c937e-7f56-4fff-aca6-b338feaa18f4).

---

**Environment (if applicable)**  
Provide relevant details about the environment where the issue occurred:  

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser : Chrome 

---

**Smartphone (please complete the following information):**

---

**Additional context**

---

**Severity**  
How critical is this issue?  
- [ ] 🔴 Critical  
- [ ] 🟠 Major  
- [X] 🟡 Minor

---

**Possible Fix**  
Suggest a fix or reason for the bug if known.

---

### Checklist  
- [X] I have searched the existing issues and this bug has not been reported yet.  
- [X] I have updated the project to the latest version.  
- [X] I have provided all the necessary details.  
- [X] I have **starred this repository**.

**Comment by Swati970** [comment]
I would like to work on this project, please assign me

**Comment by PATILYASHH** [comment]
Please assign me i created this issue
